### ISSUE TITLE
New PV Prediction card visual

### ISSUE THREAD

**Issue by pacemaker82** [pacemaker82/PV-Card-Preview#1]
@gcoan @springfall2008

I created this card view for my dashboard using Predbat's PV prediction entities. 

I find it a useful visual - thought I would mention it in case you think useful to include in the docs. 

<img width="500" height="111" alt="Image" src="https://github.com/user-attachments/assets/53ad5ffe-4bcf-4cc6-b2be-3872c3547a5b" />

ReadME: https://github.com/pacemaker82/PV-Card-Preview

**Comment by gcoan** [comment]
Another thought #pacemaker82, it would be useful to include (smaller font) the PV10 forecast as well.

I'd then be able to do away with the future forecast chart I use (I have a separate one for PV today which is worth retaining as it tracks today's generation as well as forecast)
![image](https://github.com/user-attachments/assets/d8e14d31-22f5-44ec-a716-408075f4b289)

**Comment by gcoan** [comment]
There's some serious CSS hacking going on in that code @pacemaker82 - what's the logic for that determines whether the energy reading is < 15?  I couldn't visually see anything different

I use bar card myself for showing power meters to show what's being imported, exported, battery charged, home consumption, etc.  As you say it works on single entity values

I like the visual look and feel you've achieved of the vertical PV meters, and thanks for trying different ways of representing PV10, ideally I'd like to see it on the same meter, just with a lower line/different colour.

I wonder whether energy-line-gauge https://github.com/Tomer27cz/energy-line-gauge might be a way to display multiple entries in the same line as that does that natively, vis:

![image](https://github.com/user-attachments/assets/5227bbe9-41fe-4b79-8f7e-b9c3a55c4e93)

**Comment by gcoan** [comment]
@pacemaker82 added the PV card preview to the predbat documentation

PR https://github.com/springfall2008/batpred/pull/2590

**Comment by pacemaker82** [comment]
I updated the code for it to be a little bit less hacky. I realised there was some magic numbers in there for min and max PV.

https://github.com/pacemaker82/PV-Card-Preview

The MIN_PV (magic number 15) essentially makes the bar red when my target minimum isnt met in the prediction. You wont see it much in summer...

<img width="510" height="110" alt="Image" src="https://github.com/user-attachments/assets/7e6960f8-9c41-47cc-99d2-00eb7718ddde" />

The MAX_PV is your theoretical daily max PV you might ever get. In my case thats about 35. 

I updated the code to use two new helper entities for min and max. So now the code is much cleaner, and you dont have to worry about setting the min or max in the code loads of times. Just setup the helpers and set the values once. You can also change those values easily and card "just works".

**Comment by ward0** [comment]
@pacemaker82 @gcoan 
Both modules are not found in HACS anymore (they are from mid 2020...)
bar-card (To show the bar card graphics - found in HACS)
card_mod (To manipulate the CSS in the bar card - found in HACS)

How can this still work?

**Comment by gcoan** [comment]
> Both modules are not found in HACS anymore (they are from mid 2020...)
> bar-card (To show the bar card graphics - found in HACS)
> card_mod (To manipulate the CSS in the bar card - found in HACS)

bar card is still showing in HACS for me (no hyphen in the middle), if its not, you can manually add the repository https://github.com/spacerokk/bar-card
card-mod is also showing (note the hyphen) https://github.com/thomasloven/lovelace-card-mod
